version: '3.5'
services:
   web_dev:
      build: .
      ports:
         - "4990:4990"
      volumes:
         - .:/hht
      environment:
         - ENV=development
         - PORT=4990
         - MONGODB_URI_RCP=mongodb://mongodb:27017/couchpotatoes
   mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
         - MONGO_DATA_DIR=/usr/data/db
         - MONGO_LOG_DIR=/dev/null
      volumes:
         - ./data/db:/usr/data/db
      ports:
         - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
 default:
  name: web_dev